### ISSUE TITLE
unicode table rendering in iTerm

### ISSUE THREAD

**Issue by panaak** [hirber/hirber#5]
Just a detail but it bites the eyes..) On MacOS in iTerm, the unicode vertical dashed lines are slightly shifted to the left:

![image](https://user-images.githubusercontent.com/3832812/111248691-b5091b80-860a-11eb-935e-940044dfea22.png)

any idea why is that?

Works ok in normal Terminal.app

**Comment by marzdrel** [comment]
I think this was originally done on purpose. This character definition is different from the outside of the table. Rending depends on the font. Maybe the font you are using in the normal terminal app does not distinguish those? On the screen this looks off, but that is - again - due to the font. 

Either way, you can easily fix this, but overwriting the frame definition in some of the initializers (.irbrc, etc).

```ruby
Hirb::Helpers::UnicodeTable::CHARS[:bottom][:vertical][:inside] = 
  Hirb::Helpers::UnicodeTable::CHARS[:bottom][:vertical][:outside]
```
<img width="618" alt="ss-2021-10-06_10 04 44" src="https://user-images.githubusercontent.com/225680/136163925-73209a80-a419-416c-a67e-2a5ad0d9089b.png">
