### ISSUE TITLE
Add relationships in table printing

### ISSUE THREAD

**Issue by jrz** [hirber/hirber#8]
I'd like to be able use belongs_to relationships while printing an activerecord table.

`table User.all, fields: [:id, :email, :name, "account.name" ]`
and/or
`table User.all, fields: [:id, :email, :name, ->(x) {x.name} ]`
and/or
`table User.all, fields: [:id, :email, :name, :account]`
(Last one should either print ID, to_s, or call :name)

In case of the first one (string), it would be nice to show which part of the graph is nil. For example if account was nil:
table Post.all, fields: [:id, :subject, "created_by.name", "created_by.account.name" ]

```
|  id  |  subject     |  created_by.name  |  created_by.account.name      |
===========================================================================
|  1   |  some post   |  some user        |  company account              |
|  2   |  other post  |  other user       |  <<User(4).account was nil>>  |
|  3   |  third post  |  third user       |  <<nil>>                      |
|  3   |  third post  |  third user       |  <<created_by was nil>>       |
|  3   |  third post  |  third user       |  <<nil.nil.nil>>              |
```
Example 3 shows three ways to show nil within relationships. They all have ups/downs.  RFC

**Comment by marzdrel** [comment]
Hey @jrz thanks a lot for suggestion. I am wondering, if there indeed a real value into implementing relations directly into the gem. At this point you can easily just display fields like this from generated Array. A little bit more typing, but you can get all the benefits of the formatting, including headers. 

```ruby
table User.all.map { _1.slice(:id, :email, :name).merge account_name: _1.account.name }
```

As for the `nil` - this is interesting approach. In order to get it fully functional as in the example, this would indeed required passing relation chains as strings. I am not sure if thats worth implementing just to get this backed in. 🤔
